extends:
  - ../.eslintrc.yml

rules:
  "@typescript-eslint/no-unnecessary-condition":
    - warn
    - allowConstantLoopConditions: true

  "@typescript-eslint/no-namespace": [ warn, allowDeclarations: true ]
