name: Publish
on: { push: { branches: [ main ] }, release: { types: [ created ] } }

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v4 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v4, with: { node-version: ^18.20 || ^20.10 || >=22 } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v4, with: { version: ^9, run_install: true } }
    - run: git config --global user.email github-action@users.noreply.github.com
    - run: git config --global user.name "Github Action"
    - run: pnpm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

    - name: Publish dev
      if: github.event_name == 'push'
      run: scripts/version-dev.js && pnpm package && cd dist && pnpm publish --tag dev

    - name: Publish release
      if: github.event_name == 'release'
      run: pnpm package && cd dist && pnpm publish --no-git-checks
